### ISSUE TITLE
Differences between XETLA and oneMKL/oneDNN

### ISSUE THREAD

**Issue by louie-tsai** [intel/xetla#20]
Since either oneMKL or oneDNN provides optimized GEMM and CONV implementations on Xe GPU, why users need to approach XETLA?
is xetla an open source version of oneMKL?
Good to explain the position among different intel products when intel gives more options to users.

thanks

**Comment by tdeng5** [comment]
XeTLA is a collection of SYCL/eSIMD template, target for the building block to implement high-performance GEMM, CONV and adjacent computations with reasonable efforts.
XeTLA provides reusable, flexible C++ templates for subgroup level, workgroup level, kernel level primitives. The developers can implement & optimize kernels by specializing and tuning with different data types, tiling policies, algorithms, fusion policies, etc.
XeTLA primitives try best to hide/abstract different Xe HW implementation details from SYCL/DPC++ developers.

**Comment by mgrabban** [comment]
Hello,

I understand XeTLA provides building blocks that can be convenient (for non-experts) to write efficient kernels.
But suppose I have to perform a simple matrix-matrix multiplication (maybe many times for two matrices of size 4096 x 4096). In this case is XeTLA is going to be more performant than oneMKL gemm? I am finding that the latter is faster.

**Comment by tdeng5** [comment]
For simple GEMM + specific shape which oneMKL or oneDNN can support, XeTLA could get similar performance. That's not the key user scenario for XeTLA. XeTLA could get some performance advantages when fusing some GEMM based kernels to one bit kernel.
